// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizTemplateMvcDotnet6.DatabaseSql;

#nullable disable

namespace QuizTemplateMvcDotnet6.Migrations
{
    [DbContext(typeof(QuizTemplate_DbContext))]
    [Migration("20211213103234_Sync")]
    partial class Sync
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DotNetExtra.QuizImplementation.QuizPdd_Answer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CurrentQuestionid")
                        .HasColumnType("int");

                    b.Property<int>("answerPoints")
                        .HasColumnType("int");

                    b.Property<string>("answerText")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("CurrentQuestionid");

                    b.ToTable("PddAllAnswers");
                });

            modelBuilder.Entity("DotNetExtra.QuizImplementation.QuizPdd_PictureeGetterUrl", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("currentQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("sourcePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("currentQuestionId")
                        .IsUnique();

                    b.ToTable("PddAllPictureables");
                });

            modelBuilder.Entity("DotNetExtra.QuizImplementation.QuizPdd_Question", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("questionText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("PddAllQuestions");
                });

            modelBuilder.Entity("DotNetExtra.QuizImplementation.QuizPdd_Answer", b =>
                {
                    b.HasOne("DotNetExtra.QuizImplementation.QuizPdd_Question", "CurrentQuestion")
                        .WithMany("answersItemsList")
                        .HasForeignKey("CurrentQuestionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentQuestion");
                });

            modelBuilder.Entity("DotNetExtra.QuizImplementation.QuizPdd_PictureeGetterUrl", b =>
                {
                    b.HasOne("DotNetExtra.QuizImplementation.QuizPdd_Question", "CurrentQuestion")
                        .WithOne("currentIPictureGetterStringable")
                        .HasForeignKey("DotNetExtra.QuizImplementation.QuizPdd_PictureeGetterUrl", "currentQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentQuestion");
                });

            modelBuilder.Entity("DotNetExtra.QuizImplementation.QuizPdd_Question", b =>
                {
                    b.Navigation("answersItemsList");

                    b.Navigation("currentIPictureGetterStringable")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
